import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import NavBar from './components/Nav bar/NavBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <NavBar />
        {children}
      </body>
    </html>
  )
}
